In [1]:
import numpy as np
import pandas as pd
import datetime
from data_provider import DataProvider

def generate_data(num_assets, start, end, seed):
    length = (end - start).days
    generator = np.random.default_rng(seed)
    data = []
    for _ in range(num_assets):
        d_f = pd.DataFrame(generator.standard_normal(length)).cumsum() + generator.integers(
            1, 101
        )
        trimmed = np.maximum(d_f[0].values, np.zeros(len(d_f[0].values)))
        trimmed_list = trimmed.tolist()
        # find index of first 0 element
        zero_idx = next((idx for idx, val in enumerate(trimmed_list) if val == 0), -1)
        if zero_idx >= 0:
            # set to 0 all values after first 0
            trimmed_list = [
                val if idx < zero_idx else 0 for idx, val in enumerate(trimmed_list)
            ]
        data.append(trimmed_list)
    return data

In [2]:
num_assets = 4
seed = 0

start=datetime.datetime(2016, 1, 1)
end=datetime.datetime(2016, 1, 30)

stocks = generate_data(num_assets, start, end, seed)
data = DataProvider(data=stocks)

# Print dimension of the data

#for d in data.data:
#  print(d)

mu = data.get_period_return_mean_vector()
print(mu)
sigma = data.get_period_return_covariance_matrix()
print(sigma)
skew = data.get_period_return_coskewness_tensor()
print(skew)
kurt = data.get_period_return_cokurtosis_tensor()
print(kurt)

[-0.00147451  0.00518634  0.00160436 -0.00076805]
[[ 7.99089684e-05 -3.87051703e-05 -8.36844238e-06  3.36172587e-06]
 [-3.87051703e-05  1.74863275e-04  2.43366555e-05 -2.33409678e-05]
 [-8.36844238e-06  2.43366555e-05  1.19729949e-04  2.35331069e-05]
 [ 3.36172587e-06 -2.33409678e-05  2.35331069e-05  9.91892495e-05]]
[[[ 0.171715   -0.22681102  0.21159277 ... -0.05349842 -0.56252362
    0.15372142]
  [-0.22681102 -0.34780605  0.3670601  ...  0.2132992  -0.14134029
    0.2657052 ]
  [ 0.21159277  0.3670601  -0.38559805 ... -0.20511444  0.19335339
   -0.28618893]
  ...
  [-0.05349842  0.2132992  -0.20511444 ... -0.03155463  0.35299576
   -0.11262608]
  [-0.56252362 -0.14134029  0.19335339 ...  0.35299576  0.61730996
    0.17599565]
  [ 0.15372142  0.2657052  -0.28618893 ... -0.11262608  0.17599565
   -0.29023367]]

 [[-0.22681102 -0.34780605  0.3670601  ...  0.2132992  -0.14134029
    0.2657052 ]
  [-0.34780605  0.01462716  0.05605464 ... -0.00220228  0.31942675
    0.48926219]
  [ 0.367